#ifndef _REFERENCE_THERMOCOUPLE_TEMPERATURE_READER_H_

#define _REFERENCE_THERMOCOUPLE_TEMPERATURE_READER_H_

#include "System/ThreadMacros.h"

THREAD_PROTOTYPE(ReferenceThermocoupleTemperatureReader)

void ReferenceThermocoupleTemperatureReader_setup(void);
void ReferenceThermocoupleTemperatureReader_initialize(void);
float ReferenceThermocoupleTemperatureReader_getTemperature(void);
void ReferenceThermocoupleTemperatureReader_registerDataReadyCallback(void (*dataReadyCallback)(float));
void ReferenceThermocoupleTemperatureReader_deregisterDataReadyCallback(void);

#endif
